ktor {
    deployment {
        port = 8081
        port = ${?PORT}
    }
    application {
        modules = [ com.authapi.ApplicationKt.module ]
    }
}
jwt {
    secret = "your-super-secret-jwt-key-change-in-production"
    secret = ${?JWT_SECRET}
    issuer = "auth-api"
    audience = "auth-api-users"
    realm = "Auth API"
    accessTokenExpiry = 3600000
    refreshTokenExpiry = 604800000
}
database {
    # "h2" for local testing, "postgres" for production
    mode = "postgres"
    mode = ${?DB_MODE}
    url = "jdbc:postgresql://ep-rough-mud-al6fxu6y-pooler.c-3.eu-central-1.aws.neon.tech:5432/fuelify_db?sslmode=require"
    url = ${?DATABASE_URL}
    user = "team_dev"
    user = ${?DB_USER}
    password = "fuelify2026!"
    password = ${?DB_PASSWORD}
    poolSize = 10
}
email {
    # true  = print token to console (testing)
    # false = send real Gmail (production)
    mock = false
    host = "smtp.gmail.com"
    port = "587"
    username = "fuelify2026@gmail.com"
    password = "zmwxbwoacjbclkia"
    fromName = "Fuelify"
}
app {
    baseUrl = "http://localhost:8080"
    baseUrl = ${?BASE_URL}
}
security {
    maxLoginAttempts = 5
    lockoutDurationMinutes = 15
}
groq {
  apiKey = "YOUR_API_KEY"
  apiKey = ${?GROQ_API_KEY}
}
supabase {
  url = "https://ckefpofedwbbfpicjckt.supabase.co"
  key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZWZwb2ZlZHdiYmZwaWNqY2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NTI2MDMsImV4cCI6MjA5MTMyODYwM30.bBfDzxbxeD4AeJe-QqkTQxObuAT049OFb5n-8oBvtQE"
  bucket = "images"
}
