ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.example.fuelify.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://ep-rough-mud-al6fxu6y-pooler.c-3.eu-central-1.aws.neon.tech/fuelify_db?sslmode=require"
    url = ${?DATABASE_URL}
    user = "team_dev"
    user = ${?DB_USER}
    password = "fuelify2026!"
    password = ${?DB_PASSWORD}
    driver = "org.postgresql.Driver"
    maxPoolSize = 3
}
